Traceback (most recent call last):
  File "main.py", line 11, in <module>
    prime_check([2, 44, 5, 3, 67, 17])
  File "main.py", line 5, in prime_check
    for y in range(3, x**0.5+1, 2):
TypeError: range() integer end argument expected, got float.
