Traceback (most recent call last):
  File "main.py", line 5, in <module>
    print i,
IOError: [Errno 27] File too large
