Traceback (most recent call last):
  File "main.py", line 2, in <module>
    print ("python")
IOError: [Errno 27] File too large
