Traceback (most recent call last):
  File "main.py", line 3, in <module>
    zip(dict(1,'a',2,'c'))
TypeError: dict expected at most 1 arguments, got 4
